<?php

/**
 * blog_comentarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class blog_comentarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object blog_comentarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('blog_comentario');
    }
}