<?php

/**
 * blog_articuloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class blog_articuloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object blog_articuloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('blog_articulo');
    }
}