<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/09/30 16:51:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=192.168.0.101;dbname=sergio_bd2',
  'username' => 'phs-adm',
  'password' => 'phs-adm',
  'name' => 'doctrine',
)),);
